#sonar.projectKey=MartinCHladny_Semestralka_INF2_SonarQB_3b45b5d8-1129-4f03-9fba-29ab8821c9e7
#sonar.projectKey=MartinCHladny_Semestralka_INF2_SonarQB_AZyfg4TIUuAXj2QOjNJ5
sonar.projectKey=MartinCHladny_Semestralka_INF2_SonarQB_b0a62df1-dcfc-473f-8eeb-2c69351bb5aa
